# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgY-3RF65hojeFj-7jXud_g_L-TJQtL_
"""

# Algoritmo Kaprekar 6174 (SEM STRING / SEM LISTA)

print("Digite um número de até 4 dígitos:")
num = int(input())

# ---------------- VALIDAÇÕES ----------------

# Tipo e positivo
if num < 0:
    print("Erro: número deve ser positivo")
    exit()

# Faixa
if num > 9999:
    print("Erro: número fora da faixa (0000 a 9999)")
    exit()

# ---------------- PROCESSO ----------------

contador = 0

while num != 6174:

    # Separar dígitos (com zeros à esquerda)
    d1 = num // 1000
    d2 = (num % 1000) // 100
    d3 = (num % 100) // 10
    d4 = num % 10

    # Verificar repetição (3 ou mais iguais)
    iguais = 0

    if d1 == d2 or d1 == d3 or d1 == d4:
        iguais += 1
    if d2 == d3 or d2 == d4:
        iguais += 1
    if d3 == d4:
        iguais += 1

    if iguais >= 3:
        print("Erro: muitos dígitos repetidos")
        exit()

    # -------- ORDENAÇÃO MANUAL (bubble sort simples) --------

    # Colocando em variáveis auxiliares
    a = d1
    b = d2
    c = d3
    d = d4

    # Ordenar crescente (trocas)
    if a > b:
        a, b = b, a
    if a > c:
        a, c = c, a
    if a > d:
        a, d = d, a
    if b > c:
        b, c = c, b
    if b > d:
        b, d = d, b
    if c > d:
        c, d = d, c

    # Número crescente (NDC)
    ndc = a*1000 + b*100 + c*10 + d

    # Número decrescente (NDD)
    ndd = d*1000 + c*100 + b*10 + a

    # Subtração
    resultado = ndd - ndc

    contador += 1

    print("Iteração", contador, ":", ndd, "-", ndc, "=", resultado)

    num = resultado

# ---------------- FINAL ----------------

print("\nConstante de Kaprekar (6174) atingida em", contador, "iterações.")